=== balanikas/space-rocks/levels/level_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "background": {
      "type": "string"
    },
    "soundtrack": {
      "type": "string"
    },
    "player": {
      "type": "object",
      "properties": {
        "image": {
          "type": "string"
        },
        "maneuverability": {
          "type": "integer"
        },
        "acceleration": {
          "type": "number"
        },
        "anim_on_destroy": {
          "type": "string"
        },
        "sound_on_impact": {
          "type": "string"
        },
        "damage": {
          "type": "integer"
        },
        "armor": {
          "type": "integer"
        },
        "primary_weapon": {
          "type": "object",
          "properties": {
            "damage": {
              "type": "integer"
            },
            "armor": {
              "type": "integer"
            },
            "speed": {
              "type": "integer"
            },
            "sound": {
              "type": "string"
            },
            "reload": {
              "type": "integer"
            },
            "image": {
              "type": "string"
            }
          },
          "required": [
            "damage",
            "armor",
            "speed",
            "sound",
            "reload",
            "image"
          ]
        },
        "secondary_weapon": {
          "type": "object",
          "properties": {
            "damage": {
              "type": "integer"
            },
            "armor": {
              "type": "integer"
            },
            "speed": {
              "type": "integer"
            },
            "sound": {
              "type": "string"
            },
            "reload": {
              "type": "integer"
            },
            "image": {
              "type": "string"
            }
          },
          "required": [
            "damage",
            "armor",
            "speed",
            "sound",
            "reload",
            "image"
          ]
        }
      },
      "required": [
        "image",
        "maneuverability",
        "acceleration",
        "anim_on_destroy",
        "sound_on_impact",
        "damage",
        "armor",
        "primary_weapon",
        "secondary_weapon"
      ]
    },
    "enemies": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "tiers": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "damage": {
                  "type": "integer"
                },
                "armor": {
                  "type": "integer"
                },
                "max_velocity": {
                  "type": "integer"
                },
                "min_velocity": {
                  "type": "integer"
                },
                "max_rotation": {
                  "type": "integer"
                },
                "scale": {
                  "type": [
                    "integer",
                    "number"
                  ]
                },
                "children": {
                  "type": "integer"
                },
                "sound_on_destroy": {
                  "type": "string"
                },
                "sound_on_impact": {
                  "type": "string"
                },
                "image": {
                  "type": "string"
                },
                "anim_on_destroy": {
                  "type": "string"
                }
              },
              "required": [
                "damage",
                "armor",
                "max_velocity",
                "min_velocity",
                "max_rotation",
                "scale",
                "children",
                "sound_on_destroy",
                "sound_on_impact",
                "image",
                "anim_on_destroy"
              ]
            }
          }
        },
        "required": [
          "tiers"
        ]
      }
    }
  },
  "required": [
    "background",
    "soundtrack",
    "player",
    "enemies"
  ]
}

=== balanikas/space-rocks/levels/0_level1/.json
{
    "background" : "background",
    "soundtrack" : "background",
    "player": {
        "image" : "spaceship",
        "maneuverability": 6,
        "acceleration" : 0.15,
        "anim_on_destroy" : "explosion8",
        "sound_on_impact": "hurt",
        "damage" : 5,
        "armor" : 1000,
        "primary_weapon": {
            "damage": 1,
            "armor" : 0,
            "speed": 8,
            "sound": "weapon1",
            "reload": 200,
            "image" : "bullet1"
        },
        "secondary_weapon": {
            "damage": 8,
            "armor" : 0,
            "speed": 4,
            "sound": "weapon2",
            "reload": 800,
            "image" : "bullet2"
        }
    },
    "enemies": [
        {
            "tiers": [
                {
                    "damage": 10,
                    "armor" : 1,
                    "max_velocity": 4,
                    "min_velocity": 1,
                    "max_rotation": 3,
                    "scale": 3,
                    "children": 70,
                    "sound_on_destroy": "explosion_big",
                    "sound_on_impact": "absorb1,absorb2,absorb3,absorb4",
                    "image": "planet-1",
                    "anim_on_destroy" : "explosion8"
                },
                {
                    "damage": 2,
                    "armor" : 4,
                    "max_velocity": 5,
                    "min_velocity": 2,
                    "max_rotation": 10,
                    "scale": 0.7,
                    "children": 6,
                    "sound_on_destroy": "explosion_medium",
                    "sound_on_impact": "absorb1,absorb2,absorb3,absorb4",
                    "image": "planet-1",
                    "anim_on_destroy" : "explosion8"

                },
                {
                    "damage": 1,
                    "armor" : 2,
                    "max_velocity": 10,
                    "min_velocity": 5,
                    "max_rotation": 0,
                    "scale": 0.3,
                    "children": 0,
                    "sound_on_destroy": "explosion_small",
                    "sound_on_impact": "absorb1_small,absorb2_small",
                    "image": "planet-1",
                    "anim_on_destroy" : "explosion2"
                }
            ]
        },

         {
            "tiers": [
                {
                    "damage": 10,
                    "armor" : 1,
                    "max_velocity": 4,
                    "min_velocity": 1,
                    "max_rotation": 3,
                    "scale": 2,
                    "children": 30,
                    "sound_on_destroy": "explosion_big",
                    "sound_on_impact": "absorb1,absorb2,absorb3,absorb4",
                    "image": "planet-3",
                    "anim_on_destroy" : "explosion8"
                },
                {
                    "damage": 2,
                    "armor" : 4,
                    "max_velocity": 5,
                    "min_velocity": 2,
                    "max_rotation": 10,
                    "scale": 0.7,
                    "children": 3,
                    "sound_on_destroy": "explosion_medium",
                    "sound_on_impact": "absorb1,absorb2,absorb3,absorb4",
                    "image": "planet-3",
                    "anim_on_destroy" : "explosion8"

                },
                {
                    "damage": 1,
                    "armor" : 2,
                    "max_velocity": 10,
                    "min_velocity": 5,
                    "max_rotation": 0,
                    "scale": 0.3,
                    "children": 0,
                    "sound_on_destroy": "explosion_small",
                    "sound_on_impact": "absorb1_small,absorb2_small",
                    "image": "planet-3",
                    "anim_on_destroy" : "explosion2"
                }
            ]
        },

         {
            "tiers": [
                {
                    "damage": 10,
                    "armor" : 10,
                    "max_velocity": 3,
                    "min_velocity": 1,
                    "max_rotation": 3,
                    "scale": 2,
                    "children": 3,
                    "sound_on_destroy": "explosion_big",
                    "sound_on_impact": "absorb1,absorb2,absorb3,absorb4",
                    "image": "planet-4",
                    "anim_on_destroy" : "explosion8"
                },
                {
                    "damage": 2,
                    "armor" : 4,
                    "max_velocity": 6,
                    "min_velocity": 3,
                    "max_rotation": 10,
                    "scale": 0.7,
                    "children": 3,
                    "sound_on_destroy": "explosion_medium",
                    "sound_on_impact": "absorb1,absorb2,absorb3,absorb4",
                    "image": "planet-4",
                    "anim_on_destroy" : "explosion8"

                },
                {
                    "damage": 1,
                    "armor" : 2,
                    "max_velocity": 10,
                    "min_velocity": 5,
                    "max_rotation": 0,
                    "scale": 0.3,
                    "children": 0,
                    "sound_on_destroy": "explosion_small",
                    "sound_on_impact": "absorb1_small,absorb2_small",
                    "image": "planet-4",
                    "anim_on_destroy" : "explosion2"
                }
            ]
        },

         {
            "tiers": [
                {
                    "damage": 10,
                    "armor" : 10,
                    "max_velocity": 3,
                    "min_velocity": 1,
                    "max_rotation": 3,
                    "scale": 2.5,
                    "children": 2,
                    "sound_on_destroy": "explosion_big",
                    "sound_on_impact": "absorb1,absorb2,absorb3,absorb4",
                    "image": "planet-5",
                    "anim_on_destroy" : "explosion8"
                },
                {
                    "damage": 2,
                    "armor" : 4,
                    "max_velocity": 5,
                    "min_velocity": 2,
                    "max_rotation": 10,
                    "scale": 1,
                    "children": 12,
                    "sound_on_destroy": "explosion_medium",
                    "sound_on_impact": "absorb1,absorb2,absorb3,absorb4",
                    "image": "planet-5",
                    "anim_on_destroy" : "explosion8"

                },
                {
                    "damage": 1,
                    "armor" : 2,
                    "max_velocity": 10,
                    "min_velocity": 5,
                    "max_rotation": 0,
                    "scale": 0.2,
                    "children": 0,
                    "sound_on_destroy": "explosion_small",
                    "sound_on_impact": "absorb1_small,absorb2_small",
                    "image": "planet-5",
                    "anim_on_destroy" : "explosion2"
                }
            ]
        }
    ]
}
